# for all configuration options look here:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html

server:
    port: 8080

spring:
    jackson:
        serialization:
            indent_output: true
    jmx:
        enabled: true
        default_domain: com.asseco.aha.training.sat-rest

sat-rest:
    cfg:
        author: Arny